export const races = [
  { round: '01', location: 'AUSTRALIA',     when: '08 MAR 26', laps: '58', winner: 'G. RUSSEL'    },
  { round: '02', location: 'CHINA',         when: '15 MAR 26', laps: '56', winner: 'K. ANTONELLI' },
  { round: '03', location: 'JAPAN',         when: '29 MAR 26', laps: '53', winner: 'K. ANTONELLI' },
  { round: '04', location: 'MIAMI',         when: '03 MAY 26', laps: '57', winner: 'K. ANTONELLI' },
  { round: '05', location: 'CANADA',        when: '24 MAY 26', laps: '70', winner: 'K. ANTONELLI' },
  { round: '06', location: 'MONACO',        when: '07 JUN 26', laps: '78', winner: 'TBD'          },
  { round: '07', location: 'BARCELONA',     when: '12 JUN 26', laps: '66', winner: 'TBD'          },
  { round: '08', location: 'AUSTRIA',       when: '26 JUN 26', laps: '71', winner: 'TBD'          },
  { round: '09', location: 'BRITISH',       when: '03 JUL 26', laps: '52', winner: 'TBD'          },
  { round: '10', location: 'BELGIUM',       when: '17 JUL 26', laps: '44', winner: 'TBD'          },
  { round: '11', location: 'HUNGARIAN',     when: '24 JUL 26', laps: '70', winner: 'TBD'          },
  { round: '12', location: 'DUTCH',         when: '21 AUG 26', laps: '72', winner: 'TBD'          },
  { round: '13', location: 'ITALY',         when: '04 SEP 26', laps: '53', winner: 'TBD'          },
  { round: '14', location: 'MADRID',        when: '11 SEP 26', laps: 'TBA', winner: 'TBD'          },
  { round: '15', location: 'AZERBAIJAN',    when: '24 SEP 26', laps: '51', winner: 'TBD'          },
  { round: '16', location: 'SINGAPORE',     when: '09 OCT 26', laps: '62', winner: 'TBD'          },
  { round: '17', location: 'USA',           when: '23 OCT 26', laps: '56', winner: 'TBD'          },
  { round: '18', location: 'MEXICO CITY',   when: '30 OCT 26', laps: '71', winner: 'TBD'          },
  { round: '19', location: 'BRAZIL',        when: '06 NOV 26', laps: '71', winner: 'TBD'          },
  { round: '20', location: 'LAS VEGAS',     when: '19 NOV 26', laps: '50', winner: 'TBD'          },
  { round: '21', location: 'QATAR',         when: '27 NOV 26', laps: '57', winner: 'TBD'          },
  { round: '22', location: 'ABU DHABI',     when: '04 DEC 26', laps: '58', winner: 'TBD'          },
]
