export const tracks = {
  monaco: {
    name: "Monaco",
    round: "6",
    coverLabel: "NEXT UP",
    coverNameColor: "#87001c",
    coverLabelColor: "#000000",
    coverButtonColor: "#a50000",
    coverNameFont: "font-figtree",
    coverLabelFont: "font-belanosima",
    coverNameOffset: -12,
    laps: "78",
    date_start: "05",
    date_end: "07",
    month: "JUN",
    track_length: "3.337 km",
    race_distance: "260.286 km",
    circuit_record: "1:12.909",
    record_driver: "Lewis Hamilton",
    raceDate: "2026-06-07T15:00:00",
    geo: "Monte Carlo",
    flag: "/icons/monacoflag.svg",
    facts: "The Monaco Grand Prix is the shortest and slowest race on the Formula 1 calendar.",
    schedule: {
      practice1: { label: "PRACTICE 1", date: "5 JUN", time: "13:30" },
      practice2: { label: "PRACTICE 2", date: "5 JUN", time: "17:00" },
      practice3: { label: "PRACTICE 3", date: "6 JUN", time: "12:30" },
      qualifying: { label: "QUALIFYING",  date: "6 JUN", time: "16:00" },
      race:       { label: "RACE",        date: "7 JUN", time: "15:00" },
    },
    winners: [
      { year: "2025", name: "LANDO NORRIS", description: "1x MONACO GP VICTORY|1x MONACO GP POLE", image: "/drivers/lando.avif", side: "right" },
      { year: "2024", name: "CHARLES LECLERC", description: "1x MONACO GP VICTORY|3x MONACO GP POLE", image: "/drivers/charles.avif", side: "left" },
      { year: "2023", name: "MAX VERSTAPPEN", description: "2x MONACO GP VICTORY|1x MONACO GP POLE", image: "/drivers/max.avif", side: "right" },
    ],
    colorPrimary: "#F10536",
    colorDark: "#2B030A",
    colorYear: "#660317",
    colorText: "#FFE7E7",
    colorAccent: "#FF7474",
    colorHighlight: "#FF9D9D",
    colorNavText: "#FFE7E7",
    gradientDown: "linear-gradient(to bottom, #F10536 0%, #2B030A 86.538%)",
    gradientUp: "linear-gradient(to bottom, #2B030A 0%, #F10536 86.538%)",
  },
  barcelona: {
    name: "Barcelona",
    round: "7",
    coverLabel: "ROUND 7",
    coverNameColor: "#ff7000",
    coverLabelColor: "#000000",
    coverButtonColor: "#e66805",
    coverNameFont: "font-sedgwick",
    coverLabelFont: "font-belanosima",
    coverNameOffset: 6,
    laps: "66",
    date_start: "12",
    date_end: "14",
    month: "JUN",
    track_length: "4.657 km",
    race_distance: "307.236 km",
    circuit_record: "1:16.330",
    record_driver: "Max Verstappen",
    raceDate: "2026-06-14T15:00:00",
    geo: "Catalunya",
    flag: "/icons/spainflag.svg",
    facts: "Barcelona was Formula 1's primary testing venue for decades, making it one of the most understood circuits on the calendar.",
    schedule: {
      practice1: { label: "PRACTICE 1", date: "12 JUN", time: "13:30" },
      practice2: { label: "PRACTICE 2", date: "12 JUN", time: "17:00" },
      practice3: { label: "PRACTICE 3", date: "13 JUN", time: "12:30" },
      qualifying: { label: "QUALIFYING",  date: "13 JUN", time: "16:00" },
      race:       { label: "RACE",        date: "14 JUN", time: "15:00" },
    },
    winners: [
      { year: "2025", name: "OSCAR PIASTRI", description: "1x BARCELONA GP VICTORY|1x BARCELONA GP POLE", image: "/drivers/piastri.avif", side: "right" },
      { year: "2024", name: "MAX VERSTAPPEN", description: "4x BARCELONA GP VICTORY|1x BARCELONA GP POLE", image: "/drivers/max.avif", side: "left" },
      { year: "2023", name: "MAX VERSTAPPEN", description: "4x BARCELONA GP VICTORY|1x BARCELONA GP POLE", image: "/drivers/max.avif", side: "right" },
    ],
    colorPrimary: "#E60000",
    colorDark: "#FF7700",
    colorYear: "#f6500a",
    colorText: "#FFD2BE",
    colorAccent: "#FF996B",
    colorHighlight: "#FF996B",
    colorNavText: "#FFE2CB",
    gradientDown: "linear-gradient(to bottom, #E60000 21.154%, #FF7700 86.538%)",
    gradientUp: "linear-gradient(to bottom, #FF7700 0%, #E60000 86.538%)",
  },
  austria: {
    name: "Austria",
    round: "8",
    coverLabel: "ROUND 8",
    coverNameColor: "#002884",
    coverLabelColor: "#ffffff",
    coverButtonColor: "#113477",
    coverNameFont: "font-oswald",
    coverLabelFont: "font-belanosima",
    coverNameOffset: -14,
    laps: "71",
    date_start: "26",
    date_end: "28",
    month: "JUN",
    track_length: "4.318 km",
    race_distance: "306.578 km",
    circuit_record: "1:05.619",
    record_driver: "Carlos Sainz",
    raceDate: "2026-06-28T15:00:00",
    geo: "Spielberg",
    flag: "/icons/austriaflag.svg",
    facts: "Nestled in the Austrian Alps, the Red Bull Ring has the largest elevation change of any permanent circuit on the Formula 1 calendar.",
    schedule: {
      practice1: { label: "PRACTICE 1", date: "26 JUN", time: "13:30" },
      practice2: { label: "PRACTICE 2", date: "26 JUN", time: "17:00" },
      practice3: { label: "PRACTICE 3", date: "27 JUN", time: "12:30" },
      qualifying: { label: "QUALIFYING",  date: "27 JUN", time: "16:00" },
      race:       { label: "RACE",        date: "28 JUN", time: "15:00" },
    },
    winners: [
      { year: "2025", name: "LANDO NORRIS", description: "1x AUSTRIA GP VICTORY|0x AUSTRIA GP POLE", image: "/drivers/lando.avif", side: "right" },
      { year: "2024", name: "GEORGE RUSSELL", description: "1x AUSTRIA GP VICTORY|0x AUSTRIA GP POLE", image: "/drivers/russel.avif", side: "left" },
      { year: "2023", name: "MAX VERSTAPPEN", description: "5x AUSTRIA GP VICTORY|3x AUSTRIA GP POLE", image: "/drivers/max.avif", side: "right" },
    ],
    colorPrimary: "#274B9D",
    colorDark: "#97A0FF",
    colorYear: "#4f66b3",
    colorText: "#E8EDFF",
    colorAccent: "#96B6FF",
    colorHighlight: "#96B6FF",
    colorNavText: "#D9DCFF",
    gradientDown: "linear-gradient(to bottom, #274B9D 0%, #97A0FF 86.538%)",
    gradientUp: "linear-gradient(to bottom, #97A0FF 0%, #274B9D 86.538%)",
  },
};
