export const tracks = {
  monaco: {
    name: "Monaco",
    round: "6",
    laps: "78",
    date_start: "05",
    date_end: "07",
    month: "JUN",
    track_length: "3.337 km",
    race_distance: "260.286 km",
    circuit_record: "1:12.909",
    record_driver: "Lewis Hamilton",
    geo: "Monte Carlo",
    flag: "/icons/monacoflag.svg",
    facts: "The Monaco Grand Prix is the shortest and slowest race on the Formula 1 calendar.",
    schedule: {
      practice1: { label: "PRACTICE 1", date: "5 JUN", time: "13:30" },
      practice2: { label: "PRACTICE 2", date: "5 JUN", time: "17:00" },
      practice3: { label: "PRACTICE 3", date: "6 JUN", time: "12:30" },
      qualifying: { label: "QUALIFYING",  date: "6 JUN", time: "16:00" },
      race:       { label: "RACE",        date: "7 JUN", time: "15:00" },
    },
    colorPrimary: "#F10536",
    colorDark: "#2B030A",
    colorText: "#FFE7E7",
    colorAccent: "#FF7474",
    colorHighlight: "#FF9D9D",
    colorNavText: "#FFE7E7",
    gradientDown: "linear-gradient(to bottom, #F10536 0%, #2B030A 86.538%)",
    gradientUp: "linear-gradient(to bottom, #2B030A 0%, #F10536 86.538%)",
  },
  barcelona: {
    name: "Barcelona",
    round: "7",
    laps: "66",
    date_start: "12",
    date_end: "14",
    month: "JUN",
    track_length: "4.657 km",
    race_distance: "307.236 km",
    circuit_record: "1:16.330",
    record_driver: "Max Verstappen",
    geo: "Catalunya",
    flag: "/icons/spainflag.svg",
    facts: "Barcelona was Formula 1's primary testing venue for decades, making it one of the most understood circuits on the calendar.",
    schedule: {
      practice1: { label: "PRACTICE 1", date: "12 JUN", time: "13:30" },
      practice2: { label: "PRACTICE 2", date: "12 JUN", time: "17:00" },
      practice3: { label: "PRACTICE 3", date: "13 JUN", time: "12:30" },
      qualifying: { label: "QUALIFYING",  date: "13 JUN", time: "16:00" },
      race:       { label: "RACE",        date: "14 JUN", time: "15:00" },
    },
    colorPrimary: "#E60000",
    colorDark: "#FF7700",
    colorText: "#FFD2BE",
    colorAccent: "#FF996B",
    colorHighlight: "#FF996B",
    colorNavText: "#FFE2CB",
    gradientDown: "linear-gradient(to bottom, #E60000 21.154%, #FF7700 86.538%)",
    gradientUp: "linear-gradient(to bottom, #FF7700 0%, #E60000 86.538%)",
  },
  austria: {
    name: "Austria",
    round: "8",
    laps: "71",
    date_start: "26",
    date_end: "28",
    month: "JUN",
    track_length: "4.318 km",
    race_distance: "306.578 km",
    circuit_record: "1:05.619",
    record_driver: "Carlos Sainz",
    geo: "Spielberg",
    flag: "/icons/austriaflag.svg",
    facts: "Nestled in the Austrian Alps, the Red Bull Ring has the largest elevation change of any permanent circuit on the Formula 1 calendar.",
    schedule: {
      practice1: { label: "PRACTICE 1", date: "26 JUN", time: "13:30" },
      practice2: { label: "PRACTICE 2", date: "26 JUN", time: "17:00" },
      practice3: { label: "PRACTICE 3", date: "27 JUN", time: "12:30" },
      qualifying: { label: "QUALIFYING",  date: "27 JUN", time: "16:00" },
      race:       { label: "RACE",        date: "28 JUN", time: "15:00" },
    },
    colorPrimary: "#274B9D",
    colorDark: "#97A0FF",
    colorText: "#E8EDFF",
    colorAccent: "#96B6FF",
    colorHighlight: "#96B6FF",
    colorNavText: "#D9DCFF",
    gradientDown: "linear-gradient(to bottom, #274B9D 0%, #97A0FF 86.538%)",
    gradientUp: "linear-gradient(to bottom, #97A0FF 0%, #274B9D 86.538%)",
  },
};
